name: Python CI

on:
  push:
  workflow_dispatch:

env:
  APP_NAME: my-python-app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -la

      - name: Show application name
        run: echo $APP_NAME

      - name: Check secret
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "Secret is available"
          else
            echo "Secret is missing"
            exit 1
          fi
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check Python version
        run: python --version

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest test_app.py
